# Generated by Django 3.2.6 on 2021-09-09 22:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('module_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('stream_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('last_run', models.DateTimeField(null=True)),
                ('next_run', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Running', 'Running'), ('Ready', 'Ready'), ('Disabled', 'Disabled')], default='Ready', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamRun',
            fields=[
                ('run_id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(null=True)),
                ('running', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='YES', max_length=3)),
                ('errors', models.IntegerField(default=0)),
                ('stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StreamRun_stream_id', to='base.stream')),
            ],
        ),
        migrations.CreateModel(
            name='StreamModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('module_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StreamModule_module_id', to='base.module')),
                ('stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StreamModule_stream_id', to='base.stream')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleRun',
            fields=[
                ('modulerun_id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(null=True)),
                ('running', models.BooleanField(default=True)),
                ('errors', models.IntegerField(default=0)),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StreamRun', to='base.streammodule')),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ModuleRun_run_id', to='base.streamrun')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleError',
            fields=[
                ('moduleerror_id', models.AutoField(primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=100, null=True)),
                ('error_row', models.IntegerField(blank=True)),
                ('error_data', models.TextField(blank=True, max_length=5000)),
                ('modulerun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ModuleError_run_id', to='base.modulerun')),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='streams',
            field=models.ManyToManyField(through='base.StreamModule', to='base.Stream'),
        ),
    ]
