# Generated by Django 3.2.6 on 2021-09-09 22:26

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('file', models.FilePathField(path=base.models.script_path, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='parameters',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Module_template_id', to='base.template'),
        ),
    ]
