# Generated by Django 3.2.6 on 2021-09-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210909_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='parameters',
            field=models.JSONField(default='{"debug":0}'),
        ),
    ]
