# Generated by Django 3.2.6 on 2021-09-11 13:14

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_module_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='parameters',
            field=models.JSONField(default=base.models.jsonfield_default_value),
        ),
    ]
