# Generated by Django 3.2.6 on 2021-09-21 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_module_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('period', models.IntegerField(choices=[(1, 'Every Month'), (2, 'Every Week'), (3, 'Every Weekday'), (4, 'Every Day'), (5, 'Every Day - Every 12 Hours'), (6, 'Every Day - Every 8 Hours'), (7, 'Every Day - Every 6 Hours'), (8, 'Every Day - Every 4 Hours'), (9, 'Every Day - Every 3 Hours'), (10, 'Every Day - Every 2 Hours'), (11, 'Every Day - Every 1 Hour'), (12, 'Every Day - Every 30 Min.'), (13, 'Every Day - Every 20 Min.'), (14, 'Every Day - Every 15 Min.'), (15, 'Every Day - Every 10 Min.'), (16, 'Every Day - Every 5 Min'), (17, 'Every Weekday'), (18, 'Every Weekday - Every 12 Hours'), (19, 'Every Weekday - Every 8 Hours'), (20, 'Every Weekday - Every 6 Hours'), (21, 'Every Weekday - Every 4 Hours'), (22, 'Every Weekday - Every 3 Hours'), (23, 'Every Weekday - Every 2 Hours'), (24, 'Every Weekday - Every 1 Hour'), (25, 'Every Weekday - Every 30 Min.'), (26, 'Every Weekday - Every 20 Min.'), (27, 'Every Weekday - Every 15 Min.'), (28, 'Every Weekday - Every 10 Min.'), (29, 'Every Weekday - Every 5 Min')], null=True)),
                ('status', models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')])),
                ('run_type', models.IntegerField(choices=[(1, 'Once'), (2, 'Unlimited'), (3, 'Until')])),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Schedule_stream', to='base.stream')),
            ],
        ),
    ]
