# Generated by Django 3.2.6 on 2021-09-22 15:54

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='template',
        ),
        migrations.AddField(
            model_name='module',
            name='file',
            field=models.FilePathField(null=True, path=base.models.script_path),
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
