# Generated by Django 3.2.6 on 2021-09-22 15:58

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210922_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='file',
            field=models.FilePathField(path=base.models.script_path),
        ),
    ]
