# Generated by Django 3.2.6 on 2021-09-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_schedule_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.CharField(choices=[('Every Month', 'Every Month'), ('Every Week', 'Every Week'), ('Every Weekday', 'Every Weekday'), ('Every Day', 'Every Day'), ('Every Day - Every 12 Hours', 'Every Day - Every 12 Hours'), ('Every Day - Every 8 Hours', 'Every Day - Every 8 Hours'), ('Every Day - Every 6 Hours', 'Every Day - Every 6 Hours'), ('Every Day - Every 4 Hours', 'Every Day - Every 4 Hours'), ('Every Day - Every 3 Hours', 'Every Day - Every 3 Hours'), ('Every Day - Every 2 Hours', 'Every Day - Every 2 Hours'), ('Every Day - Every 1 Hour', 'Every Day - Every 1 Hour'), ('Every Day - Every 30 Min.', 'Every Day - Every 30 Min.'), ('Every Day - Every 20 Min.', 'Every Day - Every 20 Min.'), ('Every Day - Every 15 Min.', 'Every Day - Every 15 Min.'), ('Every Day - Every 10 Min.', 'Every Day - Every 10 Min.'), ('Every Day - Every 5 Min', 'Every Day - Every 5 Min'), ('Every Weekday', 'Every Weekday'), ('Every Weekday - Every 12 Hours', 'Every Weekday - Every 12 Hours'), ('Every Weekday - Every 8 Hours', 'Every Weekday - Every 8 Hours'), ('Every Weekday - Every 6 Hours', 'Every Weekday - Every 6 Hours'), ('Every Weekday - Every 4 Hours', 'Every Weekday - Every 4 Hours'), ('Every Weekday - Every 3 Hours', 'Every Weekday - Every 3 Hours'), ('Every Weekday - Every 2 Hours', 'Every Weekday - Every 2 Hours'), ('Every Weekday - Every 1 Hour', 'Every Weekday - Every 1 Hour'), ('Every Weekday - Every 30 Min.', 'Every Weekday - Every 30 Min.'), ('Every Weekday - Every 20 Min.', 'Every Weekday - Every 20 Min.'), ('Every Weekday - Every 15 Min.', 'Every Weekday - Every 15 Min.'), ('Every Weekday - Every 10 Min.', 'Every Weekday - Every 10 Min.'), ('Every Weekday - Every 5 Min', 'Every Weekday - Every 5 Min')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='run_type',
            field=models.CharField(choices=[('Once', 'Once'), ('Unlimited', 'Unlimited'), ('Until', 'Until')], max_length=20),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], max_length=20),
        ),
    ]
