# Generated by Django 3.2.6 on 2021-10-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20210922_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('to', models.CharField(max_length=200)),
                ('cc', models.CharField(max_length=200, null=True)),
                ('sent', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Not Sent', 'Not Sent')], default='Sent', max_length=20)),
                ('run_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Notification_run_id', to='base.streamrun')),
            ],
        ),
    ]
