# Generated by Django 3.2.6 on 2021-10-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20211003_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='notification_type',
            field=models.CharField(choices=[('None', 'None'), ('Every Run', 'Every Run'), ('Every Run - When errors', 'Every Run - When errors'), ('Daily', 'Daily'), ('Daily - When errors', 'Daily - When errors'), ('Weekly Summary', 'Weekly Summary')], default='None', max_length=50),
        ),
    ]
